### PR TITLE
Bugfix/93/the title in sign up how it works block

### LINKED ISSUE #93: [SignUp] FrontEnd-01 #93 The text on the button 'Become' (How It Works block) doesn't correspond the requirements
Defect Type: UI/Usability
Severity: Trivial
Priority: Low
Reproducible: Always
Environment: Windows 10 21H2, Chrome 110.0.5481.178

Description:
The text on the button "Become a ..." doesn't match the content (How-it-Works block).

Preconditions:
The web-page on the client is opened, button "How it Works" is clicked. We're now in "How it Works" block.

Steps to reproduce:
Take a look at the button below.

Actual result:
The text on the button "Become a ..." doesn't match the content.

Image

Expected result:
The text on the button must correspond to the selected role.

### PR DESCRIPTION
**Pull request by OlhaOvsiienko**
The property name has been corrected here according to the mentor's recommendations.

### CODE REVIEW

File: src/containers/guest-home-page/how-it-works/HowItWorks.jsx [hunk 1]
```diff
@@ -40,21 +40,21 @@ const HowItWorks = () => {
...
+          array={isTutor ? tutorCardBoxArray : studentCardBoxArray}
           btnText={
-            isStudent
+            !isTutor
               ? t('guestHomePage.whatCanYouDo.learn.actionLabel')
               : t('guestHomePage.whatCanYouDo.teach.actionLabel')
           }
-          isStudent={isStudent}
-          role={isStudent ? tutor : student}
+          isTutor={isTutor} //the name of this property is changed
```
Comment (khytrykv) [inline src/containers/guest-home-page/how-it-works/HowItWorks.jsx]: You have to change the property `isStudent` also inside the CardsWithButton component.
And we don't need this comment in the code.

**Review by khytrykv — APPROVED** [review]

**Review by YaroslavChuiko — APPROVED** [review]

**Review by holus-bolus — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]
